action = 0
cred_genesis_issued_at_min = 0
current_timestamp = 0
depth = 0
nonce = 0
root = 0
rp_id = 0
signal_hash = 0

[cred_pk]
x = 0
y = 0

[inputs]
cred_expires_at = 0
cred_genesis_issued_at = 0
cred_id = 0
cred_r = [0, 0]
cred_s = 0
cred_user_id_r = 0
dlog_e = 0
dlog_s = 0
id_commitment_r = 0
issuer_schema_id = 0

[inputs.cred_hashes]
associated_data_hash = 0
claims_hash = 0

[inputs.oprf_response]
x = 0
y = 0

[inputs.oprf_response_blinded]
x = 0
y = 0

[inputs.query_inputs]
beta = 0
pk_index = 0
query_r = [0, 0]
query_s = 0

[inputs.query_inputs.merkle_proof]
mt_index = 0
siblings = [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

[[inputs.query_inputs.user_pk]]
x = 0
y = 0

[[inputs.query_inputs.user_pk]]
x = 0
y = 0

[[inputs.query_inputs.user_pk]]
x = 0
y = 0

[[inputs.query_inputs.user_pk]]
x = 0
y = 0

[[inputs.query_inputs.user_pk]]
x = 0
y = 0

[[inputs.query_inputs.user_pk]]
x = 0
y = 0

[[inputs.query_inputs.user_pk]]
x = 0
y = 0

[oprf_pk]
x = 0
y = 0

[return]
id_commitment = 0
nullifier = 0
