name: SBOM Security Pipeline


permissions:
  actions: read
  contents: write

on:
  push:
    branches:
      - sg/docker_vuln
    tags-ignore:
      - v*
  pull_request:

jobs:
  security-scan:
  runs-on: ubuntu-latest
  steps:
    - name: SBOM Generation
      uses: anchore/sbom-action@v0
      with: 
        image:
        format: spdx-json
        output-file: "${{ github.sha }}-sbom.spdx.json"
    - name: Scan SBOM
      uses: anchore/scan-action@v7
      with:
        sbom: "${{ github.sha }}-sbom.spdx.json"
        fail-build: true
        severity-cutoff: critical
